fun main ()
{
    print("student Enrollment No. : ")
    var x = readLine()!!.toLong()
    print("student Name : ")
    var y = readLine()
    print("student Branch : ")
    var z = readLine()
    print("student Class : ")
    var a = readLine()
    print("student Batch : ")
    var b = readLine()
    print("student College Name : ")
    var c = readLine()
    print("student University Name : ")
    var d = readLine()
    print("student Age : ")
    var e = readLine()!!.toInt()

    println("******************************")

    println("Enrollment No. : $x")
    println("Name : $y")
    println("Branch : $z")
    println("Class : $a")
    println("Batch : $b")
    println("College Name : $c")
    println("University name : $d")
    println("Age : $e")

}